### ISSUE TITLE
ARM/DISARM status should only come from MAVLink messages

### ISSUE THREAD

**Issue by nbrachet** [nbrachet/FlyDrones.iOS#10]
not when the user clicks on the text

**Comment by nab0y4enko** [comment]
All right. What should be displayed on the button, when I send requests to the server with the new regime, but comes another in hertbeat?

**Comment by nbrachet** [comment]
The button label should always represent is mode as reported in the heartbeat message.

**Comment by nab0y4enko** [comment]
After pressing the button, we get a dropdown list with options, right?

**Comment by nbrachet** [comment]
Yes... except there would be only one option.

**Comment by nab0y4enko** [comment]
Done in 0.1.4.3
