### ISSUE TITLE
There needs to be a bubble for arming/disarming

### ISSUE THREAD

**Issue by nbrachet** [nbrachet/FlyDrones.iOS#11]
in 0.1.4.1 clicking on the text label toggles arming/disarming, instead a bubble "menu" should be displayed with the option to arm (if the current status is disarmed) or disarm (if the current status is armed), and the command should be sent only if the user clicks on that option. So it would require 2 clicks to arm/disarm.

**Comment by nab0y4enko** [comment]
Done in 0.1.4.3

**Comment by nbrachet** [comment]
Menu label reads "ARMED" instead of "ARM"

**Comment by nbrachet** [comment]
Done in 0.1.4.4
