### ISSUE TITLE
Mode shows as "gears" instead of the actual mode (text)

### ISSUE THREAD

**Issue by nbrachet** [nbrachet/FlyDrones.iOS#12]
All that is needed is the mode itself (ie. STABILIZE, POSHOLD, etc..). No gears icon. No "Base Mode:" label. No "enabled". Not "Manual Input Enabled (81). Just "STABILIZE".

**Comment by nab0y4enko** [comment]
Done in 0.1.4.3

**Comment by nbrachet** [comment]
Invalid target_system:

```
GCS: SEQ: 31 SYSID:255 COMPID:  0 - SET_MODE: custom_mode=2 (ALT_HOLD) target_system=0 base_mode=CUSTOM_MODE
```

Should be:

```
GCS: SEQ: 31 SYSID:255 COMPID:  0 - SET_MODE: custom_mode=2 (ALT_HOLD) target_system=1 base_mode=CUSTOM_MODE
```

Assuming of course the UAS' system id is 1.

**Comment by nbrachet** [comment]
Done in 0.1.4.4
