### ISSUE TITLE
Map window shows "Show Legend" and useless toggle

### ISSUE THREAD

**Issue by nbrachet** [nbrachet/FlyDrones.iOS#17]
Useless toggle should just be removed.
"Show Legend" should be replaced with the GPS # sats in view & HDOP, both available in the [GPS_RAW_INT](https://pixhawk.ethz.ch/mavlink/#GPS_RAW_INT) mavlink message)  (N/A is the GPS fix is not available -- ie. fix_type is <= 2).

**Comment by nab0y4enko** [comment]
done in 0.1.5.1

**Comment by nbrachet** [comment]
How can it show a "copter icon" on the map, and say N/A for the GPS fix?
![screen shot 2015-06-09 at 10 53 20 am](https://cloud.githubusercontent.com/assets/7151870/8060908/d031df3e-0e95-11e5-9ba8-160cfe19c244.png)

[edit]
I'm guessing it is because the fix type is 1:

```
UAS: SEQ:  1 SYSID:  1 COMPID:  1 - GPS_RAW_INT: time_usec=1,955,822,000 lat=422,970,400 lon=-712,335,991 alt=58,390 eph=9,999 epv=65,535 vel=0 cog=2,558 fix_type=1 satellites_visible=0
```

So the GPS info should be displayed even with a fix type of 1.

**Comment by nbrachet** [comment]
HDOP is expressed in 100m in the GPS_RAW_INT message, so it needs to be divided by 100 before being displayed.

**Comment by nab0y4enko** [comment]
i.e. always displayed?

**Comment by nbrachet** [comment]
No. Just when displayed.

**Comment by nab0y4enko** [comment]
You wrote that display GPS # sats and HDOP is necessary only when fix_type is> 2.
Then you wrote that display this information, Also if fix_type == 1
Do I understand correctly?

**Comment by nbrachet** [comment]
Yes. So when fix_type >= 1. But fix_type could still be 0 when the GPS fix is not available.

**Comment by nab0y4enko** [comment]
If fix_type == 0, I should display the icon of helicopter?

**Comment by nbrachet** [comment]
If fix_type == 0 there is no GPS fix, no GPS coordinates. Where would the icon be placed?

**Comment by nab0y4enko** [comment]
Done in v0.2

**Comment by nbrachet** [comment]
fix_type == 1 still indicates there is no GPS fix -- I misread that.
So when fix_type == 1 (and GPS coordinates are still available) just draw the map but with no icon.

**Comment by nab0y4enko** [comment]
what text displayed if fixtype is 1?
"Satellites: N/A HDOP: N/A" ?

**Comment by nbrachet** [comment]
I lost it now but I have seen examples where fix_type=1 and lat/long/hdop != NA. In that case I'd display the values in the message (and keep the map at that lat/lon).
If lat/lon/hdop is not in the message then yes: N/A.

**Comment by nab0y4enko** [comment]
Done in 0.2.5.6
