### ISSUE TITLE
ARM menu doesn't disappear if UAS doesn't ARM

### ISSUE THREAD

**Issue by nbrachet** [nbrachet/FlyDrones.iOS#18]
If for whatever reason the UAS doesn't ARM, the ARM menu doesn't disappear.
It should disappear after the next heartbeat message

**Comment by nab0y4enko** [comment]
If the menu is opened and the value of arm changes, the menu disappears.
But if the heartbeat lost, then all open menus will be closed.
(v 0.1.5)

**Comment by nbrachet** [comment]
The menu should disappear even if the value doesn't change.

**Comment by nab0y4enko** [comment]
Done in v0.2
