### ISSUE TITLE
Video not showing up

### ISSUE THREAD

**Issue by nbrachet** [nbrachet/FlyDrones.iOS#21]
Started in 0.1.4

**Comment by nab0y4enko** [comment]
http://youtu.be/8_FyX-gbkv0
In the latest version:
- Video playing
- Indicators do not flicker
- Interruption of the heartbeat is processed
- Translucent (blurred) interface

**Comment by nab0y4enko** [comment]
I recorded a video, how the application works. Link in comments on GitHub

**Comment by nbrachet** [comment]
Ah yes my bad. The copter uses the H264 stream protocol which isn't supported yet.
