### ISSUE TITLE
Display STATUSTEXT onscreen

### ISSUE THREAD

**Issue by nbrachet** [nbrachet/FlyDrones.iOS#22]
When a [STATUSTEXT](https://pixhawk.ethz.ch/mavlink/#STATUSTEXT) message is received with a severity lower or equal to MAV_SEVERITY_ERROR the text should be display onscreen

**Comment by nab0y4enko** [comment]
How long will display a message?
Where exactly display a message?

**Comment by nbrachet** [comment]
> How long will display a message?

5s

> Where exactly display a message?

Middle of screen

**Comment by nab0y4enko** [comment]
done in 0.1.5.1

**Comment by nbrachet** [comment]
Text should be transparent.

**Comment by nab0y4enko** [comment]
Done in v0.2
