### ISSUE TITLE
Image goes out and back without any video

### ISSUE THREAD

**Issue by nbrachet** [nbrachet/FlyDrones.iOS#24]
![screen shot 2015-06-15 at 4 19 00 pm](https://cloud.githubusercontent.com/assets/7151870/8169853/4ccc1594-137a-11e5-9a31-e65350f1458d.png)

![screen shot 2015-06-15 at 3 39 30 pm](https://cloud.githubusercontent.com/assets/7151870/8169855/4fcf0d0a-137a-11e5-92ab-cb14c590f76a.png)

**Comment by nab0y4enko** [comment]
Can you give more details?

**Comment by nbrachet** [comment]
Not much more. I started playing the video then stopped it leaving the TCP connection alive. The screen shows the last image from the video (bottom screenshot). However once in a while the image would disappear and a black image would be displayed (top screenshot) for a few seconds, then the last image of the video would come back.

**Comment by nab0y4enko** [comment]
fixed
