### ISSUE TITLE
Video playback is falling behind

### ISSUE THREAD

**Issue by nbrachet** [nbrachet/FlyDrones.iOS#25]
The video playback starts a few seconds behind (already high), and keeps falling behind further and further. I'm measured it roughly at over 1min behind after only a few minutes of playback.
The same feed played on a macosx laptop shows less than a second latency.

**Comment by nab0y4enko** [comment]
Hi, Nick. Please make a test stream for me. I'll check and correct

**Comment by nbrachet** [comment]
Here's a [5min](https://dl.dropboxusercontent.com/u/1020551/x.h264) video, with time overlay.

**Comment by nab0y4enko** [comment]
hi Nick
I'm looking solution to the problem to the video delay
problem occurs during the decoding
ipad 3 is much worse to cope with it

## model   h264cat     app

ipad3   50fps       33fps
        25fps       23fps

ipad4   50fps       42fps
        25fps       24fps

**Comment by nbrachet** [comment]
How did you measure the app fps?

**Comment by nab0y4enko** [comment]
Hi, Nick.
I have a tool that allows me to determine speed of rendering, in opengl
Now I am doing optimization of app.
I'm using ipad mini (first generation) for testing.
It has the same processor as the ipad2 (Apple a5)

**Comment by nab0y4enko** [comment]
Nick, please, open for me the test stream

**Comment by nbrachet** [comment]
Still happening, even at 480p 15fps. Got 30 seconds behind pretty quickly.

**Comment by nab0y4enko** [comment]
fixed

**Comment by nab0y4enko** [comment]
This task still relevant?

**Comment by nbrachet** [comment]
Seems fixed.
