### ISSUE TITLE
Do not send PARAM_REQUEST_LIST when UAS is armed

### ISSUE THREAD

**Issue by nbrachet** [nbrachet/FlyDrones.iOS#29]

**Comment by nab0y4enko** [comment]
If I get the first heartbeat message and the status of "armed" - do not send PARAM_REQUEST_LIST?
Do I understand correctly?

**Comment by nbrachet** [comment]
Yes. Just use the previous settings. 
I suspect requesting the list might cause issues if the UAS is in flight. 

## 

Nick

**Comment by nab0y4enko** [comment]
Done in 0.2.4.9 and fixed in last build

**Comment by nab0y4enko** [comment]
This task still relevant?
