### ISSUE TITLE
Apparent loss of connection but no visual feedback

### ISSUE THREAD

**Issue by nbrachet** [nbrachet/FlyDrones.iOS#32]
![file jul 14 5 36 17 pm](https://cloud.githubusercontent.com/assets/7151870/8685793/29080dde-2a4f-11e5-8c61-ca9c736bcec5.png)

**Comment by nab0y4enko** [comment]
I need more details

**Comment by nbrachet** [comment]
I don't have any unfortunately: the screen was apparently locked -- ie. no menus were working, neither was the map button -- yet the "waiting for heartbeat" message wasn't shown either.

**Comment by nab0y4enko** [comment]
I can not repeat it, without access to the server

**Comment by nab0y4enko** [comment]
I can not repeat it without access to the server

**Comment by nbrachet** [comment]
Can you focus on #33 for now?

**Comment by nab0y4enko** [comment]
https://github.com/nbrachet/FlyDrones.iOS/releases/tag/0.2.5.3 https://github.com/nbrachet/FlyDrones.iOS/releases/tag/0.2.5.3

**Comment by nbrachet** [comment]
The first time the connection is lost the "waiting for heartbeat" message is shown, but not for the subsequent connection loss.

**Comment by nab0y4enko** [comment]
Fixed in the next build

**Comment by nbrachet** [comment]
Haven't seen it in a while. Closing.
