### ISSUE TITLE
Add Altitude to the display

### ISSUE THREAD

**Issue by nbrachet** [nbrachet/FlyDrones.iOS#36]
Use a similar control as the one used to display heading, but vertical on the left to display altitude (from the VFR_HUD message.)
It goes without saying that the numbers should be the actual altitude (in meters.)

**Comment by nab0y4enko** [comment]
What variant do you need?
![1](https://cloud.githubusercontent.com/assets/1070269/8761951/03713b6e-2d73-11e5-93a2-9464bcdc2803.jpg)
![2](https://cloud.githubusercontent.com/assets/1070269/8761952/0394cd22-2d73-11e5-885d-b2a8af27b32c.jpg)
![3](https://cloud.githubusercontent.com/assets/1070269/8761953/03960a66-2d73-11e5-84ae-eadbd640015d.jpg)

**Comment by nab0y4enko** [comment]
Template :)
![img_0056](https://cloud.githubusercontent.com/assets/1070269/8761958/3698fdec-2d73-11e5-8531-21f9a5c978f3.PNG)

**Comment by nbrachet** [comment]
The first variant is closer to what I had in mind... But it would have to be transparent. I like the fading effect top/bottom but they should be more pronounced so roughly only 1/4 the height is readable.

I think it's just as well to use the same control as the one for the heading, but vertically on the left. Same size.

**Comment by nab0y4enko** [comment]
Hi Nick. I understood you. I'll do it in the morning.
